### ISSUE TITLE
UI/UX[RFC]: system to enable a header bar and controlling side bar render order

### ISSUE THREAD

**Issue by janaka** [docqai/docq#103]
## Situation
Streamlit's default design isn't a great UX. There are a few key building blocks missing that results in a bit of a clunky UX.

For example, Streamlist doesn't appear to have an OOTB way to control placing components a bar at the top or controlling rendering ordering the side-bar when Page Links are enabled for nav.

## Solution

Research the recommended patterns for solving this problem. Are there any extra components that aren't in core or any third part template/layout systems we can adopt rather than developing our own? Does Tailwind CSS have any design systems that would work with Streamlit?

- first develop a proposal to communicate the approach.
- then develop quick prototype implementation to illustrate the concrete design

**Comment by janaka** [comment]
@osala-eng when researching this did you look into using the ST menu in the top right? It is possible to add custom menu items.

I'm wondering, UX and implementation-wise, if we can move all the admin stuff to the top right and use the left bar for more in-context options such as new chat, change thread etc.

Any thoughts?

**Comment by osala-eng** [comment]
dropping this for now.
