### ISSUE TITLE
CORE: Types of spaces

### ISSUE THREAD

**Issue by cwang** [docqai/docq#19]
**Is your feature request related to a problem? Please describe.**

Right now spaces are manual upload only in terms of how documents are loaded. With a **type** property we can support more loading source locations and strategies, and open doors in the future for plugins to function at this stage of the end-to-end flow.

**Describe the solution you'd like**

An additional property of `type` (wording may vary) that is saved with each space. 

**Describe alternatives you've considered**

N/A

**Additional context**

First additional type could be a web scraper.

**Comment by janaka** [comment]
@cwang have you started this already?

if so, what does the structure look like? If not I can take it. 

I've had to semi-implement in-mem for the Azure blob integration. 

`data_source_type`: enum value (`LOCAL_FILE_SYSTEM`, `AZURE_BLOB_CONTAINER`, etc.)
`data_source_config`:  dict - contains connection string and auth type value needed for the data source type.

was imagining these two would be columns on the `space` table.

**Comment by cwang** [comment]
#43 implementation
