### ISSUE TITLE
BUG: Thread spaces being shown in dropdown

### ISSUE THREAD

**Issue by janaka** [docqai/docq#192]
Only shared spaces should be show in this drop down list 

![Image](https://github.com/docqai/docq/assets/51779/6e1dd453-565d-4613-aa46-ece1c9f0420a)

**Comment by osala-eng** [comment]
@janaka This only shows in branches without the updated code from the thread space PR should be fixed once it's been merged.

**Comment by janaka** [comment]
ah, yes. confirmed. My branch hasn't been rebased. sorry.

**Comment by janaka** [comment]
Actually, my agents branch is current with `main`. `main` also shows the issue. Maybe there's a fix in your fileuploader branch as that seems to be ok.

Let's hold until that's merged.

**Comment by osala-eng** [comment]
Fixed by #187
