### ISSUE TITLE
RFC: Offering API-based external integrations

### ISSUE THREAD

**Issue by cwang** [docqai/docq#22]
**Is your change proposal related to a problem? Please describe.**

Beyond the internal, plugin-based method of integration, Docq should offer external-facing, API-based integration mostly for interfacing with the segregated, indexed private data for other organisational use. 

**Propose the solution you'd like**

Modularising the core part of the application and creating an API front alongside the existing Streamlit-based UI front.

**Describe alternatives you've considered**

Could hack Streamlit to retrofit an API interface;
Or rewrite UI completely to be API-based therefore rearchitecting the whole application into backend -> API -> frontend.

**Additional context**

It's a medium-term goal so priority-wise, it should give way to other big features.

**Comment by janaka** [comment]
Approach-wise, practically probably best to start by adding a few simple endpoints needed to drive requirements like a browser extension #26. Over time if there demand for richer functionality over the API then our current UI should be re-built on the API so we are naturally dogfooding the API.

**Comment by janaka** [comment]
Streamlit hack used to drop down to the tornado server layer to implement REST endpoints
