### ISSUE TITLE
RFC: Adding 'organisation' support for users and spaces

### ISSUE THREAD

**Issue by cwang** [docqai/docq#44]
**Is your change proposal related to a problem? Please describe.**

Right now Docq has a flat structure for both users and spaces. Adding an *org* level should address some real-world segregation and grouping use cases.

**Propose the solution you'd like**

Adding an *org* level means for any given user,
- They belong to their personal org by default, where they're an admin user for it.
- They can create more orgs and invite others to join the org. 

With this shift, users will be scoped by org; the same for spaces. 

**Describe alternatives you've considered**

N/A

**Additional context**

Docq is designed to be a single-tenant system but it may change in the future. This feature may have implications when Docq switches to a multi-tenant architecture.

**Comment by janaka** [comment]
Re-multi-tenancy for SaaS discussion. This is probably the solution. Ues `Organisation` as the partition key for everything.

**Comment by janaka** [comment]
A thought on multi-tenant, maybe that shouldn't be in the OSS version. Otherwise feels like we are making it easy for somebody else to start offering SaaS.

**Comment by janaka** [comment]
- add method to valid if a user belongs to an org
- add the selected org to the auth context.
- when the user login default to their personal org
- add DAL for `Organisations`
- add Org management UI
  - create and list orgs
- update add user UI to handle inviting existing users. 
- update `_get_path()` to include the org id as the second segment. persistence should be an org subfolder within `index`, `sqlite`, and `upload`.
- `Users` and `Organisations` are the only sqlite files that should live outside an org folder.

**Comment by janaka** [comment]
@cwang thoughts: Should the personal chat be scoped to an org context or not associated with the org, rather associated directly to and only to a user?

I'm leaning towards the latter, associate with a user, no org context.

**Comment by janaka** [comment]
Note: I decided not to go down the path of creating a default org for a user for now. I think that's warranted when self service sign up is implemented. Doing this would also require reworking the personal ask feature IMO otherwise it would be confusing. This MVP version assumes we'll (super admins) will set up orgs and create the initial user(s).

**Comment by cwang** [comment]
> @cwang thoughts: Should the personal chat be scoped to an org context or not associated with the org, rather associated directly to and only to a user?
> 
> I'm leaning towards the latter, associate with a user, no org context.

Two reasons why I'd vote for the former:
1. In an enterprise context (which this org feature mostly likely finds itself in), it's likely that personal chats are NOT personal as recent ChatGPT ban shows. I'd rather making a **personal** org which belongs to an individual, than making the exception here.
2. For simplicity, presumably it'd be a simple, blanket change if we don't make any exception about it?

**Comment by cwang** [comment]
> Note: I decided not to go down the path of creating a default org for a user for now. I think that's warranted when self service sign up is implemented. Doing this would also require reworking the personal ask feature IMO otherwise it would be confusing. This MVP version assumes we'll (super admins) will set up orgs and create the initial user(s).

That's absolutely fine for now. What's likely to happen is the system creates a personal org as the first org for self-service sign-ups. That could be done as part of SaaSifying effort

**Comment by janaka** [comment]
@cwang what was your original thinking when deciding to put all the chat-related data in the usage DB under personal? The need here is to have chat partitioned by user right?

**Comment by cwang** [comment]
Not saying we drop it. What I'm saying is that personal != your own in any enterprise context and we shouldn't create loop hole that may go against ourselves :) If a user wants, they can create an entire personal org to do what they want in an isolated org. 

Re the original design thinking for personal chat - yes, it was before the org. Have been suggesting refectoring the personal space disk file structure lately in anticipation for the org feature a few times.
