### ISSUE TITLE
UX: Consolidate Space management into a single view

### ISSUE THREAD

**Issue by janaka** [docqai/docq#52]
**Is your feature request related to a problem? Please describe.**
Currently, Space create, edit, and archiving is handled in the Admin Overview section. While document management for a space is in the Admin Docs section. This is clunky, there's some overlap in functionality, and should be improved.

As a side effect this will eliminate the problem where navigating between the two view by clicking Manage Documents causing the user to login again.

**Describe the solution you'd like**
Consolidate on a single screen based on the current Admin Docs view. Bring space creation and editing here.

Create Space: add a `Create Space` tab, same pattern as create new user.

Edit Space: add an `Edit` button in the Space Details tab, and bring over the same Spaces edit form UI Admin Overview. 

**Describe alternatives you've considered**
Other version of the UI will involve a lot more work. The above seems like low effort.

**Additional context**
- [x] Make sure navigating directly with a query string param works
- [x] Make sure switching space using the DDL works

**Comment by janaka** [comment]
The new consolidated section should be called `Admin Spaces`

**Comment by osala-eng** [comment]
> The new consolidated section should be called `Admin Spaces`

Okay ranaming the consolidated space as `Admin Spaces` and doing away with `Admin Docs`
