### ISSUE TITLE
CORE: Links to sources in shared spaces need to be made space aware

### ISSUE THREAD

**Issue by cwang** [docqai/docq#56]
**Describe the bug**

I (@cwang) added error handling code to wrap around the problem with the function https://github.com/docqai/docq/blob/b5c7185cfaff46c7c466837cb3bf724b801d0cae/source/docq/manage_documents.py#L65

The root cause, afaik is that the code assumes all documents exist in one's personal space, which fails to take documents from shared spaces into consideration. 

In order to fix this, the system needs to be able to locate documents not only from a personal space but also any shared space.  

**To Reproduce**
Steps to reproduce the behaviour:

1. Click "Ask Shared Documents"
2. Ask a question
3. See that the source part of the response now says "Unable to list sources" which is the error handing code in action 

**Expected behaviour**

It should work the same way, with correct, downloadable links for all the source references.

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu 22.04, macOS 11.4]
- Code Version [e.g. 1.1.0]
- Other Runtime Versions (please list below)

**Additional context**

N/A

**Comment by janaka** [comment]
@osala-eng also maybe have look at using `source_node.extra_info` rather than regex on the node text.

Note that in #48 the metadata in `extra_info` will be different given it will be a website and page URL rather than filename and page number.

**Comment by cwang** [comment]
In fact the source links are now completely broken in any space (personal or shared) @osala-eng could you fix it as the most urgent issue pls

**Comment by osala-eng** [comment]
> In fact the source links are now completely broken in any space (personal or shared) @osala-eng could you fix it as the most urgent issue pls

Yes, already working on it.
