### ISSUE TITLE
RFC: Support unlimited number of personal spaces and pass-through chat sessions

### ISSUE THREAD

**Issue by cwang** [docqai/docq#87]
**Is your change proposal related to a problem? Please describe.**

If you use chatgpt or some other public chatbots, you can save and restore historic chat sessions by topics. I think we should:

- Support unlimited chat sessions, saved and reactivated, like chatgpt
- Support unlimited personal spaces, each of which can host file uploads or ingest from a data source

This would empower individual users without needing setup from group admins.

**Propose the solution you'd like**

Database + UI/UX changes await. 

I believe we're using a separate location for any personal data. Maybe it's a good time to align the storage centrally?

**Describe alternatives you've considered**

N/A

**Additional context**

Still debatable whether we should allow individual users to do so?

**Comment by janaka** [comment]
Implemented in #88
